// src/components/CardRender.vue
<template>
  <div class="card-render" :style="{ width: cardWidth + 'px' }">
    <canvas ref="canvasRef" :width="cardWidth" :height="cardHeight"></canvas>
  </div>
</template>

<script setup>
import { ref, watch, onMounted, computed } from 'vue'

const props = defineProps({
  card: {
    type: Object,
    required: true
  }
})

const canvasRef = ref(null)
const resourcePath = ref('')

const CARD_WIDTH = 325
const CARD_HEIGHT = 474
const SCALE = CARD_WIDTH / 813

const cardWidth = computed(() => CARD_WIDTH)
const cardHeight = computed(() => CARD_HEIGHT)

const frameMap = {
  'normal': 'monster_ys',
  'effect': 'monster_ys',
  'ritual': 'monster_ys',
  'fusion': 'monster_ys',
  'synchro': 'monster_ys',
  'xyz': 'monster_xg',
  'pendulum': 'monster_tt',
  'link': 'monster_lj',
  'spell': 'spell',
  'trap': 'trap'
}

const attributeMap = {
  'light': 'light',
  'dark': 'dark',
  'fire': 'fire',
  'water': 'water',
  'wind': 'wind',
  'earth': 'earth',
  'divine': 'divine'
}

async function loadResourcePath() {
  if (window.electronAPI) {
    resourcePath.value = await window.electronAPI.getResourcePath()
  }
}

function drawCard() {
  const canvas = canvasRef.value
  if (!canvas) return

  const ctx = canvas.getContext('2d')
  ctx.clearRect(0, 0, CARD_WIDTH, CARD_HEIGHT)

  drawFrame(ctx)
  drawPicture(ctx)
  drawAttribute(ctx)
  drawLevelStars(ctx)
  drawName(ctx)
  drawRace(ctx)
  drawDescription(ctx)
  drawAttackDefense(ctx)
  drawCopyright(ctx)
  if (props.card.holoEffect) {
    drawHoloEffect(ctx)
  }
}

function drawFrame(ctx) {
  const frameName = props.card.type === 'monster'
    ? (props.card.type2 === 'pendulum' ? 'monster_tt_lb' : `monster_ys`)
    : (props.card.type === 'spell' ? 'spell' : 'trap')

  ctx.fillStyle = '#1a1a2e'
  ctx.fillRect(0, 0, CARD_WIDTH, CARD_HEIGHT)

  ctx.strokeStyle = '#ffd700'
  ctx.lineWidth = 2
  ctx.strokeRect(2, 2, CARD_WIDTH - 4, CARD_HEIGHT - 4)
}

function drawPicture(ctx) {
  const pos = { x: 40 * SCALE, y: 88 * SCALE, w: 245 * SCALE, h: 246 * SCALE }

  ctx.fillStyle = '#333'
  ctx.fillRect(pos.x, pos.y, pos.w, pos.h)

  if (props.card.customImageData) {
    const img = new Image()
    img.onload = () => {
      ctx.drawImage(img, pos.x, pos.y, pos.w, pos.h)
    }
    img.src = 'data:image/jpeg;base64,' + props.card.customImageData
  }
}

function drawAttribute(ctx) {
  const attr = attributeMap[props.card.attribute] || 'dark'
  const pos = { x: 272 * SCALE, y: 23 * SCALE, w: 30 * SCALE, h: 30 * SCALE }

  ctx.fillStyle = getAttributeColor(props.card.attribute)
  ctx.beginPath()
  ctx.arc(pos.x + pos.w / 2, pos.y + pos.h / 2, pos.w / 2, 0, Math.PI * 2)
  ctx.fill()

  ctx.fillStyle = '#fff'
  ctx.font = `bold ${14 * SCALE}px sans-serif`
  ctx.textAlign = 'center'
  ctx.textBaseline = 'middle'
  ctx.fillText(getAttributeText(props.card.attribute), pos.x + pos.w / 2, pos.y + pos.h / 2)
}

function getAttributeColor(attr) {
  const colors = {
    'light': '#ffff00',
    'dark': '#800080',
    'fire': '#ff0000',
    'water': '#0000ff',
    'wind': '#00ff00',
    'earth': '#8b4513',
    'divine': '#ffd700'
  }
  return colors[attr] || '#800080'
}

function getAttributeText(attr) {
  const texts = {
    'light': '光',
    'dark': '暗',
    'fire': '炎',
    'water': '水',
    'wind': '风',
    'earth': '地',
    'divine': '神'
  }
  return texts[attr] || '暗'
}

function drawLevelStars(ctx) {
  if (props.card.type !== 'monster') return

  const level = props.card.level || 0
  const pos = { x: 274 * SCALE, y: 58 * SCALE }

  for (let i = 0; i < level && i < 12; i++) {
    const x = pos.x - i * 22 * SCALE
    drawStar(ctx, x, pos.y, 10 * SCALE)
  }
}

function drawStar(ctx, x, y, size) {
  ctx.fillStyle = '#ffd700'
  ctx.beginPath()
  for (let i = 0; i < 5; i++) {
    const angle = (i * 4 * Math.PI) / 5 - Math.PI / 2
    const px = x + Math.cos(angle) * size
    const py = y + Math.sin(angle) * size
    if (i === 0) ctx.moveTo(px, py)
    else ctx.lineTo(px, py)
  }
  ctx.closePath()
  ctx.fill()
}

function drawName(ctx) {
  const pos = { x: 26 * SCALE, y: 38 * SCALE }

  ctx.fillStyle = props.card.attribute === 'dark' ? '#fff' : '#000'
  ctx.font = `bold ${26 * SCALE}px sans-serif`
  ctx.textAlign = 'left'
  ctx.textBaseline = 'middle'

  const name = props.card.name || '未命名'
  ctx.fillText(name, pos.x, pos.y)
}

function drawRace(ctx) {
  if (props.card.type !== 'monster') return

  const pos = { x: 21 * SCALE, y: 366 * SCALE }
  const raceText = `${props.card.race || ''}`

  ctx.fillStyle = '#000'
  ctx.font = `${10 * SCALE}px sans-serif`
  ctx.textAlign = 'left'
  ctx.textBaseline = 'middle'
  ctx.fillText(raceText, pos.x, pos.y)
}

function drawDescription(ctx) {
  const pos = { x: 26 * SCALE, y: 377 * SCALE }
  const maxWidth = 273 * SCALE
  const lineHeight = 11 * SCALE
  const maxLines = 6
  const fontSize = 10 * SCALE

  ctx.fillStyle = '#000'
  ctx.font = `${fontSize}px sans-serif`
  ctx.textAlign = 'left'
  ctx.textBaseline = 'top'

  const text = props.card.desc || ''
  const lines = wrapText(ctx, text, maxWidth, maxLines)

  lines.forEach((line, i) => {
    if (i < maxLines) {
      ctx.fillText(line, pos.x, pos.y + i * lineHeight)
    }
  })
}

function wrapText(ctx, text, maxWidth, maxLines) {
  const words = text.split('')
  const lines = []
  let currentLine = ''

  for (const word of words) {
    const testLine = currentLine + word
    const metrics = ctx.measureText(testLine)

    if (metrics.width > maxWidth && currentLine !== '') {
      lines.push(currentLine)
      currentLine = word
      if (lines.length >= maxLines) break
    } else {
      currentLine = testLine
    }
  }

  if (currentLine && lines.length < maxLines) {
    lines.push(currentLine)
  }

  return lines
}

function drawAttackDefense(ctx) {
  if (props.card.type !== 'monster') return

  const isLink = props.card.type2 === 'link'
  const atkPos = { x: 234 * SCALE, y: 443 * SCALE }
  const defPos = { x: 300 * SCALE, y: 443 * SCALE }

  ctx.font = `bold ${14 * SCALE}px sans-serif`
  ctx.textAlign = 'center'
  ctx.textBaseline = 'middle'

  ctx.fillStyle = '#000'

  if (isLink) {
    const linkCount = props.card.linkMarkers?.filter(Boolean).length || 0
    ctx.fillText(`LINK-${linkCount}`, defPos.x, defPos.y)
  } else {
    ctx.fillText(`${props.card.attack || 0}`, atkPos.x, atkPos.y)
    ctx.fillText(`${props.card.defense || 0}`, defPos.x, defPos.y)
  }
}

function drawCopyright(ctx) {
  const pos = { x: CARD_WIDTH - 10 * SCALE, y: CARD_HEIGHT - 15 * SCALE }

  ctx.fillStyle = '#888'
  ctx.font = `${7 * SCALE}px sans-serif`
  ctx.textAlign = 'right'
  ctx.textBaseline = 'bottom'

  const text = props.card.copyright || '©KONAMI'
  ctx.fillText(text, pos.x, pos.y)
}

function drawHoloEffect(ctx) {
  ctx.fillStyle = 'rgba(255, 255, 255, 0.1)'
  ctx.fillRect(0, 0, CARD_WIDTH, CARD_HEIGHT)
}

watch(() => props.card, () => {
  drawCard()
}, { deep: true })

onMounted(async () => {
  await loadResourcePath()
  drawCard()
})
</script>

<style scoped>
.card-render {
  position: relative;
  border-radius: 8px;
  overflow: hidden;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
}

.card-render canvas {
  display: block;
  width: 100%;
  height: auto;
}
</style>

// src/components/CardRender.jsx
import { useEffect, useRef, useState } from 'react'
import { ATTRIBUTE_COLORS } from '../config/cardConstants'

const CARD_SIZES = {
  monster: { width: 318, height: 468 },
  spell: { width: 318, height: 468 },
  trap: { width: 318, height: 468 },
}

const CARD_FRAME_COLORS = {
  monster: '#700000',
  spell: '#006600',
  trap: '#660066',
}

const FRAME_BORDER_COLORS = {
  monster: '#c9a04f',
  spell: '#c9a04f',
  trap: '#c9a04f',
}

const ATTRIBUTE_SYMBOLS = {
  dark: 'D',
  divine: 'D',
  earth: 'E',
  fire: 'F',
  light: 'L',
  water: 'W',
  wind: 'W',
}

function drawLevelStars(ctx, level, x, y) {
  ctx.fillStyle = '#FFD700'
  const starSize = 13
  for (let i = 0; i < Math.min(level, 12); i++) {
    const xPos = x + (i % 4) * starSize
    const yPos = y - Math.floor(i / 4) * starSize
    drawStar(ctx, xPos, yPos, 5, 6, 3)
  }
}

function drawStar(ctx, cx, cy, spikes, outerRadius, innerRadius) {
  let rot = Math.PI / 2 * 3
  let x = cx
  let y = cy
  const step = Math.PI / spikes

  ctx.beginPath()
  ctx.moveTo(cx, cy - outerRadius)
  for (let i = 0; i < spikes; i++) {
    x = cx + Math.cos(rot) * outerRadius
    y = cy + Math.sin(rot) * outerRadius
    ctx.lineTo(x, y)
    rot += step

    x = cx + Math.cos(rot) * innerRadius
    y = cy + Math.sin(rot) * innerRadius
    ctx.lineTo(x, y)
    rot += step
  }
  ctx.lineTo(cx, cy - outerRadius)
  ctx.closePath()
  ctx.fill()
}

function drawAttributeIcon(ctx, attribute, x, y) {
  const attrColor = ATTRIBUTE_COLORS[attribute] || '#666666'
  ctx.fillStyle = attrColor
  ctx.beginPath()
  ctx.arc(x, y, 14, 0, Math.PI * 2)
  ctx.fill()
  
  ctx.fillStyle = '#FFFFFF'
  ctx.font = 'bold 14px Arial'
  ctx.textAlign = 'center'
  ctx.textBaseline = 'middle'
  ctx.fillText(ATTRIBUTE_SYMBOLS[attribute] || '?', x, y)
}

export default function CardRender({ card }) {
  const canvasRef = useRef(null)
  const [imageLoaded, setImageLoaded] = useState(false)

  useEffect(() => {
    const canvas = canvasRef.current
    if (!canvas) return

    const ctx = canvas.getContext('2d')
    const { width, height } = CARD_SIZES[card.cardType] || CARD_SIZES.monster
    const cardType = card.cardType || 'monster'

    canvas.width = width
    canvas.height = height

    const frameColor = CARD_FRAME_COLORS[cardType]
    const borderColor = FRAME_BORDER_COLORS[cardType]

    ctx.fillStyle = '#000000'
    ctx.fillRect(0, 0, width, height)

    ctx.fillStyle = frameColor
    ctx.fillRect(4, 4, width - 8, height - 8)

    ctx.fillStyle = '#F5E6C8'
    ctx.fillRect(7, 7, width - 14, height - 14)

    ctx.strokeStyle = borderColor
    ctx.lineWidth = 2
    ctx.strokeRect(7, 7, width - 14, height - 14)

    ctx.fillStyle = '#000000'
    ctx.fillRect(9, 9, width - 18, 46)
    ctx.strokeStyle = borderColor
    ctx.strokeRect(9, 9, width - 18, 46)

    ctx.fillStyle = '#F5E6C8'
    ctx.font = 'bold 18px Arial'
    ctx.textAlign = 'center'
    ctx.textBaseline = 'middle'
    const name = card.name || '???'
    const displayName = name.length > 14 ? name.substring(0, 14) : name
    ctx.fillText(displayName, width / 2, 34)

    if (cardType === 'monster') {
      const attrX = 28
      const attrY = 72
      drawAttributeIcon(ctx, card.attribute || 'earth', attrX, attrY)

      const level = parseInt(card.level) || 4
      drawLevelStars(ctx, level, width - 28, 72)

      ctx.fillStyle = '#C0C0C0'
      ctx.fillRect(12, 84, width - 24, 200)
      ctx.strokeStyle = borderColor
      ctx.lineWidth = 2
      ctx.strokeRect(12, 84, width - 24, 200)

      ctx.strokeStyle = '#000000'
      ctx.lineWidth = 1
      ctx.strokeRect(14, 86, width - 28, 196)

      if (card.imagePath) {
        const img = new Image()
        img.crossOrigin = 'anonymous'
        img.onload = () => {
          const imgWidth = width - 32
          const imgHeight = 192
          const scale = Math.min(imgWidth / img.width, imgHeight / img.height)
          const drawWidth = img.width * scale
          const drawHeight = img.height * scale
          const imgX = 16 + (imgWidth - drawWidth) / 2
          const imgY = 88 + (imgHeight - drawHeight) / 2
          ctx.drawImage(img, imgX, imgY, drawWidth, drawHeight)
          setImageLoaded(true)
        }
        img.src = card.imagePath
      }

      ctx.fillStyle = '#FFFFFF'
      ctx.font = 'bold 11px Arial'
      ctx.textAlign = 'left'
      ctx.fillText(card.race || '', 16, 295)

      ctx.fillStyle = '#000000'
      ctx.fillRect(12, 300, width - 24, 80)

      ctx.fillStyle = '#FFFFFF'
      ctx.font = '11px Arial'
      ctx.textAlign = 'left'
      const effect = card.effect || ''
      const effectLines = wrapText(ctx, effect, width - 40, 11)
      effectLines.slice(0, 4).forEach((line, i) => {
        ctx.fillText(line, 16, 314 + i * 14)
      })

      ctx.fillStyle = '#000000'
      ctx.fillRect(width - 70, height - 50, 60, 36)
      ctx.strokeStyle = borderColor
      ctx.strokeRect(width - 70, height - 50, 60, 36)

      ctx.fillStyle = '#FF0000'
      ctx.font = 'bold 11px Arial'
      ctx.textAlign = 'center'
      ctx.fillText('ATK', width - 40, height - 36)

      ctx.fillStyle = '#FFFFFF'
      ctx.font = 'bold 16px Arial'
      ctx.fillText((card.attack || 0).toString(), width - 40, height - 18)

      ctx.fillStyle = '#000000'
      ctx.fillRect(width - 70, height - 86, 60, 36)
      ctx.strokeStyle = borderColor
      ctx.strokeRect(width - 70, height - 86, 60, 36)

      ctx.fillStyle = '#0000FF'
      ctx.font = 'bold 11px Arial'
      ctx.fillText('DEF', width - 40, height - 72)

      ctx.fillStyle = '#FFFFFF'
      ctx.font = 'bold 16px Arial'
      ctx.fillText((card.defense || 0).toString(), width - 40, height - 54)

    } else {
      ctx.fillStyle = '#E8E8E8'
      ctx.fillRect(12, 64, width - 24, 220)
      ctx.strokeStyle = borderColor
      ctx.lineWidth = 2
      ctx.strokeRect(12, 64, width - 24, 220)

      ctx.strokeStyle = '#000000'
      ctx.lineWidth = 1
      ctx.strokeRect(14, 66, width - 28, 216)

      if (card.imagePath) {
        const img = new Image()
        img.crossOrigin = 'anonymous'
        img.onload = () => {
          const imgWidth = width - 32
          const imgHeight = 212
          const scale = Math.min(imgWidth / img.width, imgHeight / img.height)
          const drawWidth = img.width * scale
          const drawHeight = img.height * scale
          const imgX = 16 + (imgWidth - drawWidth) / 2
          const imgY = 68 + (imgHeight - drawHeight) / 2
          ctx.drawImage(img, imgX, imgY, drawWidth, drawHeight)
          setImageLoaded(true)
        }
        img.src = card.imagePath
      }

      const typeText = cardType === 'spell' ? '魔法' : '陷阱'
      ctx.fillStyle = '#000000'
      ctx.fillRect(12, 300, width - 24, 80)

      ctx.fillStyle = '#FFFFFF'
      ctx.font = 'bold 11px Arial'
      ctx.textAlign = 'left'
      ctx.fillText(`[${typeText}]`, 16, 314)

      ctx.font = '11px Arial'
      const desc = card.effect || card.description || ''
      const descLines = wrapText(ctx, desc, width - 40, 11)
      descLines.slice(0, 3).forEach((line, i) => {
        ctx.fillText(line, 16, 330 + i * 14)
      })
    }

    ctx.fillStyle = '#000000'
    ctx.fillRect(12, height - 40, width - 24, 30)
    ctx.strokeStyle = borderColor
    ctx.strokeRect(12, height - 40, width - 24, 30)

    ctx.fillStyle = '#666666'
    ctx.font = '10px Arial'
    ctx.textAlign = 'left'
    ctx.fillText(card.password || '00000000', 18, height - 20)

    ctx.fillStyle = '#666666'
    ctx.font = '8px Arial'
    ctx.textAlign = 'center'
    ctx.fillText('YU-GI-OH!', width / 2, height - 20)

  }, [card])

  function wrapText(ctx, text, maxWidth, fontSize) {
    ctx.font = `${fontSize}px Arial`
    const words = text.split('')
    const lines = []
    let currentLine = ''

    for (const char of words) {
      const testLine = currentLine + char
      const metrics = ctx.measureText(testLine)
      if (metrics.width > maxWidth && currentLine !== '') {
        lines.push(currentLine)
        currentLine = char
      } else {
        currentLine = testLine
      }
    }
    if (currentLine) {
      lines.push(currentLine)
    }
    return lines
  }

  return (
    <div className="card-render-container">
      <canvas
        ref={canvasRef}
        style={{
          borderRadius: '8px',
          boxShadow: '0 4px 20px rgba(0, 0, 0, 0.4)',
        }}
      />
    </div>
  )
}
